name: Deploy Nuxt site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: nuxt
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build with Nuxt (manual workaround)
        run: |
          echo "Starting build process..."
          
          # Try building, but continue even if it fails
          if npm run build; then
            echo "✓ npm run build succeeded"
          else
            echo "⚠ npm run build failed, but client files might still be available"
          fi
          
          echo "Checking what was actually built..."
          if [ -d ".nuxt" ]; then
            echo "✓ .nuxt directory exists"
            find .nuxt -name "*.css" -o -name "*.js" | head -10
          else
            echo "✗ .nuxt directory missing!"
            exit 1
          fi
          
          if [ -d ".nuxt/dist" ]; then
            echo "✓ .nuxt/dist exists"
          else
            echo "✗ .nuxt/dist missing!"
            exit 1
          fi
          
          if [ -d ".nuxt/dist/client" ]; then
            echo "✓ .nuxt/dist/client exists"
            ls -la .nuxt/dist/client/
          else
            echo "✗ .nuxt/dist/client missing!"
            exit 1
          fi
          
          echo "Creating output directory..."
          mkdir -p .output/public
          
          echo "Copying client files..."
          cp -r .nuxt/dist/client/* .output/public/
          echo "Client files copied successfully"
          
          echo "Copying favicon..."
          if [ -f "public/favicon.ico" ]; then
            cp public/favicon.ico .output/public/
            echo "Favicon copied successfully"
          else
            echo "WARNING: favicon.ico not found in public/"
          fi
          
          echo "Listing all files in .nuxt/dist/client/_nuxt/..."
          ls -la .nuxt/dist/client/_nuxt/
          
          echo "Listing all files in .output/public/_nuxt/..."
          ls -la .output/public/_nuxt/
          
          echo "Verifying specific files exist in source..."
          if [ -f ".nuxt/dist/client/_nuxt/entry.B1goDtUc.css" ]; then
            echo "✓ Source CSS file exists ($(wc -c < .nuxt/dist/client/_nuxt/entry.B1goDtUc.css) bytes)"
          else
            echo "✗ Source CSS file missing!"
            echo "Available CSS files in source:"
            find .nuxt/dist/client -name "*.css"
          fi
          
          if [ -f ".nuxt/dist/client/_nuxt/C52IU5KB.js" ]; then
            echo "✓ Source JS file exists ($(wc -c < .nuxt/dist/client/_nuxt/C52IU5KB.js) bytes)"
          else
            echo "✗ Source JS file missing!"
            echo "Available JS files in source:"
            find .nuxt/dist/client -name "*.js" | head -5
          fi
          
          echo "Verifying copied files exist..."
          if [ -f ".output/public/_nuxt/entry.B1goDtUc.css" ]; then
            echo "✓ Copied CSS file exists ($(wc -c < .output/public/_nuxt/entry.B1goDtUc.css) bytes)"
          else
            echo "✗ Copied CSS file missing!"
            echo "Available CSS files in destination:"
            find .output/public -name "*.css"
          fi
          
          if [ -f ".output/public/_nuxt/C52IU5KB.js" ]; then
            echo "✓ Copied JS file exists ($(wc -c < .output/public/_nuxt/C52IU5KB.js) bytes)"
          else
            echo "✗ Copied JS file missing!"
            echo "Available JS files in destination:"
            find .output/public -name "*.js" | head -5
          fi
          
          echo "Creating index.html..."
          cat > .output/public/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Legend in the Mist</title>
            <link rel="icon" type="image/x-icon" href="/LegendintheMist/favicon.ico">
            <link rel="stylesheet" href="/LegendintheMist/_nuxt/entry.B1goDtUc.css">
          </head>
          <body>
            <div id="__nuxt"></div>
            <script type="module" src="/LegendintheMist/_nuxt/C52IU5KB.js"></script>
          </body>
          </html>
          EOF
          
          echo "Verifying index.html content..."
          cat .output/public/index.html
        env:
          NUXT_APP_BASE_URL: /LegendintheMist/
      
      - name: Add .nojekyll file
        run: touch .output/public/.nojekyll
      
      - name: Check for CSS files
        run: |
          echo "Checking for CSS files..."
          find .output/public -name "*.css" -type f
          echo "Checking _nuxt directory..."
          ls -la .output/public/_nuxt/ || echo "No _nuxt directory found"
      
      - name: List output directory
        run: ls -la .output/public/
      
      - name: Final verification before upload
        run: |
          echo "=== FINAL VERIFICATION ==="
          echo "Checking if critical files exist before upload..."
          
          if [ -f ".output/public/index.html" ]; then
            echo "✓ index.html exists"
          else
            echo "✗ index.html missing!"
            exit 1
          fi
          
          # Check for CSS file with flexible naming
          CSS_FILE=$(find .output/public/_nuxt -name "entry.*.css" | head -1)
          if [ -n "$CSS_FILE" ] && [ -f "$CSS_FILE" ]; then
            echo "✓ CSS file exists: $(basename $CSS_FILE) ($(wc -c < $CSS_FILE) bytes)"
          else
            echo "✗ Entry CSS file missing!"
            echo "Available CSS files:"
            find .output/public -name "*.css" -type f || echo "No CSS files found"
            exit 1
          fi
          
          # Check for main JS file (largest one)
          JS_FILE=$(find .output/public/_nuxt -name "*.js" -exec ls -la {} \; | sort -k5 -nr | head -1 | awk '{print $9}')
          if [ -n "$JS_FILE" ] && [ -f "$JS_FILE" ]; then
            echo "✓ Main JS file exists: $(basename $JS_FILE) ($(wc -c < $JS_FILE) bytes)"
          else
            echo "✗ Main JS file missing!"
            echo "Available JS files:"
            find .output/public -name "*.js" -type f | head -5 || echo "No JS files found"
            exit 1
          fi
          
          # Update index.html with actual file names if they differ
          ACTUAL_CSS=$(basename $CSS_FILE)
          ACTUAL_JS=$(basename $JS_FILE)
          
          echo "Updating index.html with actual file names: CSS=$ACTUAL_CSS, JS=$ACTUAL_JS"
          
          cat > .output/public/index.html << EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Legend in the Mist</title>
            <link rel="icon" type="image/x-icon" href="/LegendintheMist/favicon.ico">
            <link rel="stylesheet" href="/LegendintheMist/_nuxt/$ACTUAL_CSS">
          </head>
          <body>
            <div id="__nuxt"></div>
            <script type="module" src="/LegendintheMist/_nuxt/$ACTUAL_JS"></script>
          </body>
          </html>
          EOF
          
          echo "All critical files verified. Proceeding with upload..."
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
