name: Deploy Nuxt site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: nuxt
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build with Nuxt (manual workaround)
        run: |
          echo "Starting build process..."
          npm run build || echo "Build failed but continuing with manual process..."
          
          echo "Creating output directory..."
          mkdir -p .output/public
          
          echo "Copying client files..."
          if [ -d ".nuxt/dist/client" ]; then
            cp -r .nuxt/dist/client/* .output/public/
            echo "Client files copied successfully"
          else
            echo "ERROR: .nuxt/dist/client directory not found!"
            exit 1
          fi
          
          echo "Copying favicon..."
          if [ -f "public/favicon.ico" ]; then
            cp public/favicon.ico .output/public/
            echo "Favicon copied successfully"
          else
            echo "WARNING: favicon.ico not found in public/"
          fi
          
          echo "Listing all files in .nuxt/dist/client/_nuxt/..."
          ls -la .nuxt/dist/client/_nuxt/
          
          echo "Listing all files in .output/public/_nuxt/..."
          ls -la .output/public/_nuxt/
          
          echo "Verifying specific files exist..."
          if [ -f ".output/public/_nuxt/entry.B1goDtUc.css" ]; then
            echo "✓ CSS file exists"
          else
            echo "✗ CSS file missing!"
            ls -la .output/public/_nuxt/*.css || echo "No CSS files found"
          fi
          
          if [ -f ".output/public/_nuxt/C52IU5KB.js" ]; then
            echo "✓ JS file exists"
          else
            echo "✗ JS file missing!"
            ls -la .output/public/_nuxt/*.js || echo "No JS files found"
          fi
          
          echo "Creating index.html..."
          cat > .output/public/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta charset="utf-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <title>Legend in the Mist</title>
            <link rel="icon" type="image/x-icon" href="/LegendintheMist/favicon.ico">
            <link rel="stylesheet" href="/LegendintheMist/_nuxt/entry.B1goDtUc.css">
          </head>
          <body>
            <div id="__nuxt"></div>
            <script type="module" src="/LegendintheMist/_nuxt/C52IU5KB.js"></script>
          </body>
          </html>
          EOF
          
          echo "Verifying index.html content..."
          cat .output/public/index.html
        env:
          NUXT_APP_BASE_URL: /LegendintheMist/
      
      - name: Add .nojekyll file
        run: touch .output/public/.nojekyll
      
      - name: Check for CSS files
        run: |
          echo "Checking for CSS files..."
          find .output/public -name "*.css" -type f
          echo "Checking _nuxt directory..."
          ls -la .output/public/_nuxt/ || echo "No _nuxt directory found"
      
      - name: List output directory
        run: ls -la .output/public/
      
      - name: Final verification before upload
        run: |
          echo "=== FINAL VERIFICATION ==="
          echo "Checking if critical files exist before upload..."
          
          if [ -f ".output/public/index.html" ]; then
            echo "✓ index.html exists"
          else
            echo "✗ index.html missing!"
            exit 1
          fi
          
          if [ -f ".output/public/_nuxt/entry.B1goDtUc.css" ]; then
            echo "✓ CSS file exists ($(wc -c < .output/public/_nuxt/entry.B1goDtUc.css) bytes)"
          else
            echo "✗ CSS file missing!"
            exit 1
          fi
          
          if [ -f ".output/public/_nuxt/C52IU5KB.js" ]; then
            echo "✓ JS file exists ($(wc -c < .output/public/_nuxt/C52IU5KB.js) bytes)"
          else
            echo "✗ JS file missing!"
            exit 1
          fi
          
          echo "All critical files verified. Proceeding with upload..."
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
